name: Add Execute Permissions to Binaries

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  add-permissions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Find and chmod binaries
        run: |
          find . -type f -executable -exec chmod +x {} \;
          find . -type f -name "*.sh" -exec chmod +x {} \;

      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Commit changes
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config --global user.name "PeterSuh-Q3"
          git config --global user.email dante9000@gmail.com        
          git add .
          git commit -m "Add execute permissions to binaries"
          git push
